StokMvc/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokMvc.Models.Entity;

namespace StokMvc.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index()
        {
            var kategoriler = db.tblkategori.ToList();
            return View(kategoriler);
        }

        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKategori(tblkategori p)
        {
            db.tblkategori.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriSil(int id)
        {
            var ktg = db.tblkategori.Find(id);
            db.tblkategori.Remove(ktg);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KategoriGetir(int id)
        {
            var ktgr = db.tblkategori.Find(id);
            return View("KategoriGetir", ktgr);
        }

        public ActionResult KategoriGuncelle(tblkategori p)
        {
            var ktg = db.tblkategori.Find(p.id);
            ktg.ad = p.ad;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

StokMvc/Views/Kategori/Index.cshtml
@using StokMvc.Models.Entity
@model List<tblkategori>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class=" table table-bordered">
    <tr>
        <th>ID</th>
        <th>KATEGORİ ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.ad</td>
            <td> <a href="/Kategori/KategoriSil/@x.id" class="btn btn-danger">Sil</a> </td>
            <td> <a href="/Kategori/KategoriGetir/@x.id" class="btn btn-warning">Güncelle</a> </td>
        </tr>
    }
</table>
<a href="/Kategori/YeniKategori" class="btn btn-primary">Yeni Kategori</a>

StokMvc/Views/Kategori/KategoriGetir.cshtml
@model StokMvc.Models.Entity.tblkategori
@{
    ViewBag.Title = "KategoriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
    <h2>Kategori Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
}

StokMvc/Views/Kategori/YeniKategori.cshtml
@model StokMvc.Models.Entity.tblkategori
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<form method="post">


    <h2>Yeni Kategori Ekleme</h2>
    <br />
    <label>Kategori Adını Giriniz...</label>
    <input type="text" class="form-control" name="ad" placeholder="Kategori Adı" /> <br />
    <button class="btn btn-info">Kaydet</button>

</form>