StokMvc/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokMvc.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace StokMvc.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        DbMvcStokEntities db = new DbMvcStokEntities();
        public ActionResult Index(int sayfa = 1)
        {
            // var musteriliste = db.tblmusteri.ToList();
            var musteriliste = db.tblmusteri.Where(x => x.durum == true).ToList().ToPagedList(sayfa, 3);
            return View(musteriliste);
        }

        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(tblmusteri p)
        {
            p.durum = true;
            db.tblmusteri.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriSil(tblmusteri p)
        {
            var musteribul = db.tblmusteri.Find(p.id);
            musteribul.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult MusteriGetir(int id)
        {
            var mus = db.tblmusteri.Find(id);
            return View("MusteriGetir", mus);
;       }

        public ActionResult MusteriGuncelle(tblmusteri p)
        {
            var mus = db.tblmusteri.Find(p.id);
            mus.ad = p.ad;
            mus.soyad = p.soyad;
            mus.sehir = p.sehir;
            mus.bakiye = p.bakiye;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

StokMvc/Views/Musteri/Index.cshtml
@using StokMvc.Models.Entity
@using PagedList
@using PagedList.Mvc
@model  PagedList.IPagedList<tblmusteri>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<table class=" table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>ŞEHİR</th>
        <th>BAKİYE</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.ad</td>
            <td>@x.soyad</td>
            <td>@x.sehir</td>
            <td>@x.bakiye</td>
            <td> <a href="/Musteri/MusteriSil/@x.id" class="btn btn-danger">Sil</a> </td>
            <td> <a href="/Musteri/MusteriGetir/@x.id" class="btn btn-warning">Güncelle</a> </td>
        </tr>
    }
</table>

@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))

<a href="/Musteri/YeniMusteri" class="btn btn-primary">Yeni Müşteri</a>

StokMvc/Views/Musteri/MusteriGetir.cshtml
@model StokMvc.Models.Entity.tblmusteri
@{
    ViewBag.Title = "MusteriGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{
    <h2>Müşteri Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.soyad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.sehir, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.bakiye, new { @class = "form-control" })
    <br />
  
    <button class="btn btn-warning">Güncelle</button>
}

StokMvc/Views/Musteri/YeniMusteri.cshtml
@model StokMvc.Models.Entity.tblmusteri
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">


    <h2>Yeni Müşteri Ekleme</h2>
    <br />
    <label>Müşteri Adını Giriniz...</label>
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" }) <br />
    <br />
    <label>Müşteri Soyadını Giriniz...</label>
    @Html.TextBoxFor(x => x.soyad, new { @class = "form-control" }) <br />
    <br />
    <label>Şehir Giriniz...</label>
    @Html.TextBoxFor(x => x.sehir, new { @class = "form-control" }) <br />
    <br />
    <label>Bakiye Giriniz...</label>
    @Html.TextBoxFor(x => x.bakiye, new { @class = "form-control" }) <br />
    <br />
   
    <button class="btn btn-info">Kaydet</button>

</form>