StokMvc/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokMvc.Models.Entity;

namespace StokMvc.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        DbMvcStokEntities db = new DbMvcStokEntities(); 
        public ActionResult Index()
        {
            var urunler = db.tblurunler.Where(x => x.durum == true).ToList();
            return View(urunler);
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> ktg = (from x in db.tblkategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.ad,
                                            Value = x.id.ToString()
                                        }).ToList();
            ViewBag.drop = ktg;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(tblurunler t)
        {
            var ktgr = db.tblkategori.Where(x => x.id == t.tblkategori.id).FirstOrDefault();
            t.tblkategori = ktgr;
            db.tblurunler.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> kat = (from x in db.tblkategori.ToList()
                                        select new SelectListItem
                                        {
                                            Text = x.ad,
                                            Value = x.id.ToString()
                                        }).ToList();
            var ktgr = db.tblurunler.Find(id);
            ViewBag.urunkategori = kat;
            return View("UrunGetir", ktgr);
        }

        public ActionResult UrunGuncelle(tblurunler p)
        {
            var urun = db.tblurunler.Find(p.id);
            urun.ad = p.ad;
            urun.marka = p.marka;
            urun.stok = p.stok;
            urun.alisfiyat = p.alisfiyat;
            urun.satisfiyat = p.satisfiyat;
            var ktg = db.tblkategori.Where(x => x.id == p.tblkategori.id).FirstOrDefault();
            urun.kategori = ktg.id;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UrunSil(tblurunler p)
        {
            var urunbul = db.tblurunler.Find(p.id);
            urunbul.durum = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

StokMvc/Views/Urun/Index.cshtml
@using StokMvc.Models.Entity
@model List<tblurunler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<table class=" table table-bordered">
    <tr>
        <th>ID</th>
        <th>ÜRÜN ADI</th>
        <th>MARKA</th>
        <th>STOK</th>
        <th>ALIŞ FİYAT</th>
        <th>SATIŞ FİYAT</th>
        <th>KATEGORİ</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.ad</td>
            <td>@x.marka</td>
            <td>@x.stok</td>
            <td>@x.alisfiyat</td>
            <td>@x.satisfiyat</td>
            <td>@x.tblkategori.ad</td> 
            <td> <a href="/Urun/UrunSil/@x.id" class="btn btn-danger">Sil</a> </td>
            <td> <a href="/Urun/UrunGetir/@x.id" class="btn btn-warning">Güncelle</a> </td>
        </tr>
    }
</table>
<a href="/Urun/YeniUrun/" class="btn btn-primary">Yeni Ürün Girişi</a>

StokMvc/Views/Urun/UrunGetir.cshtml
@model StokMvc.Models.Entity.tblurunler
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{
    <h2>Ürün Güncelleme</h2>
    @Html.HiddenFor(x => x.id, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.marka, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.stok, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.alisfiyat, new { @class = "form-control" })
    <br />
    @Html.TextBoxFor(x => x.satisfiyat, new{ @class = "form-control" })
    <br />
    @Html.DropDownListFor(x => x.tblkategori.id, (List<SelectListItem>)ViewBag.urunkategori, new { @class = "form-control" })
    <br />

    <button class="btn btn-warning">Güncelle</button>
}

StokMvc/Views/Urun/YeniUrun.cshtml
@model StokMvc.Models.Entity.tblurunler
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">


    <h2>Yeni Ürün Ekleme</h2>
    <br />
    <label>Ürün Adını Giriniz...</label>
    @Html.TextBoxFor(x => x.ad, new { @class = "form-control" }) <br />
    <br />
    <label>Marka Adını Giriniz...</label>
    @Html.TextBoxFor(x => x.marka, new { @class = "form-control" }) <br />
    <br />
    <label>Stok Miktarını Giriniz...</label>
    @Html.TextBoxFor(x => x.stok, new { @class = "form-control" }) <br />
    <br />
    <label>Alış Fyatını Giriniz...</label>
    @Html.TextBoxFor(x => x.alisfiyat, new { @class = "form-control" }) <br />
    <br />
    <label>Satış Fyatını Giriniz...</label>
    @Html.TextBoxFor(x => x.satisfiyat, new { @class = "form-control" }) <br />
    <br />
    <label>Kategori</label>
    @Html.DropDownListFor(x => x.tblkategori.id,(List<SelectListItem>)ViewBag.drop,new { @class="form-control"}) <br />

    <button class="btn btn-info">Kaydet</button>

</form>